log_level: INFO
redis:
  host: localhost
  port: 6379
  stream_id: aggregate
  input_stream_prefix: JetsonOrin
  output_stream_prefix: trackletmerger
prometheus_port: 8000
save_directory: './results'
refresh_interval: 10000 # in millsecond, 10s
last_process_interval: 60000 # in millsecond, 60s
last_processing_frame: 8919

sct_merging_config:
  enable_sct_rematch: True
  max_frame_gap: 45
  max_pixel_distance_ratio: 0.2 # less than 1
  cosine_threshold: 0.2
  static_filter: True

merging_config:
  input_stream_ids: 
    - stream1
    - stream2
    - stream3
    - stream4
    # - stream5
    # - stream6
  original_img_size:
    stream1: [2560, 1440]
    stream2: [2560, 1440]
    stream3: [2560, 1440]
    stream4: [2560, 1440]
    stream5: [2560, 1440]
    stream6: [2560, 1440]
  zone_data:
    stream1: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/imagesc001/imagesc001_zone_data_processed.json'
    stream2: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/imagesc002/imagesc002_zone_data_processed.json'
    stream3: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/imagesc003/imagesc003_zone_data_processed.json'
    stream4: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/imagesc004/imagesc004_zone_data_processed.json'
    stream5: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/imagesc001/imagesc001_zone_data_processed.json'
    stream6: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/imagesc002/imagesc002_zone_data_processed.json'
  output_stream_id: merger
  matching_metric: Cosine_Distance
  dis_thre: 0.4 # threshold for the distance metric(default cosine distance)
  dis_remove: 0.4 # threshold for the distance metric for hard remove the tracklet pair
  dis_alpha: 1 # alpha is for the apperance distance metric
  dis_beta: 0.8 # beta is for the temporal spatial metric
  searching_time: 300 # in millonsecond, for SCT merging, the searching time is the time window for searching the tracklet in the ego camera
  lost_time: 35000 # in millonsecond, for SCT merging, the lost time is the time window for the tracklet to be considered as lost
  is_clm: True # whether to use camera link model for cross-camera matching
  clm_path: 'cam_pair.json' # path to the camera pair json file (The result for camera link model)
  clm_bandwidth: 5 # bandwidth for the kernel density estimation in CLM
  kde_threshold: 5e-4 # threshold for the kernel density estimation in CLM
  frame_window: 2500 # for MCT merging, the frame window is the time window for matching tracklets in different cameras
  overlap_frames: 1500 # for MCT merging, the overlap frames is the number of frames to overlap between two cameras
  matching_algorithm: Greedy # Matching algorithm: Greedy or Hungarian

  camera_pairs: 
    - [stream1, stream2]
    - [stream2, stream3]
    - [stream3, stream4]
    - [stream4, stream5]
    - [stream5, stream6]